
# 此配置只适合开发测试环境，详细配置参考： http://t.cn/A64RaHJm
server:
  port: 5004
  servlet:
    context-path: /xxl-job-admin

# xxl
xxl:
  job:
    i18n: zh_CN
    logretentiondays: 30
    triggerpool:
      fast.max: 200
      slow.max: 200

# mybatis
mybatis:
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml

# spring
spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:pig-register}:${NACOS_PORT:8848}
        metadata:
          management.context-path: ${server.servlet.context-path}/actuator
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:pig-mysql}:${MYSQL_PORT:3306}/${MYSQL_DB:pig_job}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PWD:root}
  mvc:
    static-path-pattern: /static/**
  freemarker:
    suffix: .ftl
    request-context-attribute: request
    settings:
      number_format: 0.##########
  mail:
    host: smtp.mxhichina.com
    port: 465
    from: xxxx@gitee.wang
    username: xxxx@gitee.wang
    password: xxxx
    properties:
      mail:
        smtp:
          auth: true
          ssl.enable: true
          starttls.enable: false
          required: false
# spring boot admin 配置

management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
