server:
  port: 4001

spring:
  application:
    name: pig-config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/cqzqxq_lxh/pig-config.git
---
spring:
  profiles: dev
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://pig:gip6666@localhost:1025/eureka
---
spring:
  profiles: prd
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://pig:gip6666@pig-eureka:1025/eureka
