server:
  port: 8848   #如何修改 pig-register 启动端口 >: https://t.cn/A6XGvTdb
  tomcat:
    basedir: logs
  error:
    include-message: always

db:
  num: 1
  user: ${MYSQL_USER:root}
  password: ${MYSQL_PWD:root}
  url:
    0: jdbc:mysql://${MYSQL_HOST:pig-mysql}:${MYSQL_PORT:3306}/${MYSQL_DB:pig_config}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true


nacos:
  core:
    auth:
      server:
        identity:
          key: serverIdentity
          value: security
      plugin.nacos.token.secret.key: SecretKey012345678901234567890123456789012345678901234567890123456789
      system.type: nacos
  security:
    ignore:
      urls: /actuator/**,/,/error,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/v1/auth/**,/v1/console/health/**,/actuator/**,/v1/console/server/**

spring:
  datasource:
    platform: mysql  #这个过期属性不能修改，nacos 代码对此有硬编码
  security:
    enabled: true
  boot:  # 接入 spring boot admin
    admin:
      client:
        url: http://pig-monitor:5001
        username: pig
        password: pig
        instance:
          service-host-type: ip
  application:
    name: @project.artifactId@
  main:
    allow-circular-references: true

useAddressServer: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      influx:
        enabled: false
      elastic:
        enabled: false
